//
// DO NOT EDIT - File generated by the org.cthing.property-key-constants Gradle plugin.
//

package org.cthing.test;

/**
 * Constants for property keys in:
 * <ul>
 *   <li>prop1.properties</li>
 *   <li>prop2.properties</li>
 * </ul>
 */
@SuppressWarnings("all")
public final class Constants {

    public static final String PROP1_KEY1 = "key1";
    public static final String PROP1_KEY2 = "key2";

    public static final String PROP2_ABC_DEF_17 = "abc.def.17";
    public static final String PROP2_UVW_XYZ_18 = "uvw.xyz.18";

    private Constants() { }
}
