//
// DO NOT EDIT - File generated by the org.cthing.property-key-constants Gradle plugin.
//

package org.cthing.test;

/**
 * Constants for property keys in:
 * <ul>
 *   <li>prop1.properties</li>
 *   <li>prop2.properties</li>
 * </ul>
 */
@SuppressWarnings("all")
final class Constants {

    static final String KEY1 = "key1";
    static final String KEY2 = "key2";

    static final String ABC_DEF_17 = "abc.def.17";
    static final String UVW_XYZ_18 = "uvw.xyz.18";

    private Constants() { }
}
